import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const projectRoot = path.resolve(__dirname, "../..");
const pageSource = fs.readFileSync(
  path.join(projectRoot, "src/app/page.tsx"),
  "utf8",
);
const heroSectionSource = fs.readFileSync(
  path.join(projectRoot, "src/components/home/HomeHeroSection.tsx"),
  "utf8",
);
const layoutSource = fs.readFileSync(
  path.join(projectRoot, "src/app/layout.tsx"),
  "utf8",
);
const translationsSource = fs.readFileSync(
  path.join(projectRoot, "assets/translations/jp.ts"),
  "utf8",
);

test("home page composes the shared top bar and hero section", () => {
  assert.match(pageSource, /import PageTopBar from/);
  assert.match(pageSource, /<PageTopBar \/>/);
  assert.match(pageSource, /<HomeHeroSection \/>/);
});

test("home hero section uses translation-backed hero content", () => {
  assert.match(heroSectionSource, /translations\.home\.hero/);
  assert.match(heroSectionSource, /<h1[\s\S]*\{title\}[\s\S]*<\/h1>/);
  assert.match(
    heroSectionSource,
    /<p[\s\S]*\{description\}[\s\S]*<\/p>/,
  );
});

test("starter template content is removed from the home page", () => {
  assert.doesNotMatch(pageSource, /next\/image/);
  assert.doesNotMatch(pageSource, /To get started, edit the page\.tsx file\./);
  assert.doesNotMatch(pageSource, /Deploy Now/);
  assert.doesNotMatch(pageSource, /Documentation/);
});

test("project metadata no longer uses create-next-app defaults", () => {
  assert.match(layoutSource, /title: "Jisha"/);
  assert.match(
    layoutSource,
    /description: "Initial project page for the Jisha application"/,
  );
  assert.doesNotMatch(layoutSource, /Create Next App/);
  assert.doesNotMatch(layoutSource, /Generated by create next app/);
});

test("japanese translation file defines only the required home keys", () => {
  assert.match(translationsSource, /home:/);
  assert.match(translationsSource, /hero:/);
  assert.match(translationsSource, /title:/);
  assert.match(translationsSource, /description:/);
});
